### ISSUE TITLE
Getting error Failed to connect to MySQL: No such file or directory

### ISSUE THREAD

**Issue by jonairey** [rap2hpoutre/mysql-xplain-xplain#10]
Hi,

I've configured PHP and MySQL to work, and the following page displays connected:

```
<?php

$conn = mysql_connect('localhost', 'root', '');

if($conn) {
    echo 'Connected';
} else {
	echo 'Error: ' . mysql_errno() . ' - ' . mysql_error();
}
```

I've installed the application with Composer and am on the page http://localhost/xplain/public/config.php

When I type my credentials and hit Submit I get the following error message:

`Failed to connect to MySQL: No such file or directory`

Please help.

**Comment by rap2hpoutre** [comment]
Does it work if you set a password to your database user?

**Comment by jonairey** [comment]
If I use a user that has a password I get the same issue.

**Comment by drbissonnette** [comment]
Don't you need a database name?

$conn = mysql_connect('localhost', 'root', '','databasename')
