### ISSUE TITLE
problème avec les dépendance et PHP 7.2

### ISSUE THREAD

**Issue by Esysteme** [rap2hpoutre/mysql-xplain-xplain#12]
Bonjour,

je sais que ce n'ai pas chez vous, mais dans la dépendance du layer mysql: 

```
Warning: Declaration of Jasny\MySQL\DB::query($query) should be compatible with mysqli::query($query, $resultmode = NULL) in /data/www/myexplain/vendor/jasny/db-mysql/src/Jasny/MySQL/DB.php on line 0
Fatal error: Class Jasny\MySQL\DB_Exception may not inherit from final class (mysqli_sql_exception) in /data/www/myexplain/vendor/jasny/db-mysql/src/Jasny/MySQL/DB/Exception.php on line 0

```

**Comment by rap2hpoutre** [comment]
Bonjour ! Merci pour votre contribution. Malheureusement, cette librairie est seulement compatible avec les anciennes versions de PHP (5, cf https://github.com/rap2hpoutre/mysql-xplain-xplain/blob/master/.travis.yml), et je ne la maintiens plus vraiment (juste pour des petites demandes). Mettre à jour la librairie vers php7 demanderait trop de travail pour une librairie finalement assez confidentielle (je veux dire par là : peu utilisée).

Je reste à votre disposition pour toute question (et désolé pour le délai de réponse :/)
