### ISSUE TITLE
Fatal error occured

### ISSUE THREAD

**Issue by koriym** [rap2hpoutre/mysql-xplain-xplain#6]
```
Fatal error: Class Jasny\MySQL\DB_Exception may not inherit from final class (mysqli_sql_exception) in /foo/mysql-xplain-xplain/vendor/jasny/db-mysql/src/Jasny/MySQL/DB/Exception.php on line 60 
```

It seems `mysqli_sql_exception` changed to have `final` keyword.
I run with [PHP7](http://php-osx.liip.ch/).

**Comment by rap2hpoutre** [comment]
Confirmed. It's a problem in a vendor dependency: https://github.com/jasny/db-mysql/issues/8
Don't know what to do right now, I opened a discussion here: https://redd.it/47btk2

**Comment by koriym** [comment]
Thank you for your quick response.

**Comment by rap2hpoutre** [comment]
Ok, I think it will not be fixed in jasny/db-mysql. Feel free to send a PR if you want to remove the jasny/db-mysql dependency.
