### ISSUE TITLE
Touche TAB

### ISSUE THREAD

**Issue by mioux** [rap2hpoutre/mysql-xplain-xplain#8]
J'ai fait une petite modif dans ma version. La touche Tab envoie un "\t" dans le textarea au lieu de changer d'input.

Est-ce que ça peut vous intéresser ? Si oui, je lance une pull request :+1:

**Comment by rap2hpoutre** [comment]
Bonjour ! Merci pour ta participation !!
C'est pourquoi que tu as besoin de mettre des \t ?

**Comment by mioux** [comment]
J'utilise pas mal l'outil en ce moment, je suis en train d'optimiser les index qui sont posés sur une appli.

Le problème étant que le code est généré par un ORM et donc assez illisible

Je formate la requête dans le textarea, donc machinalement, j'utilise le bouton TAB pour réindenter mes requêtes.

D'ailleurs, je suis en train de regarder pour intégere codemirror pour la coloration syntaxique aussi :smile:

**Comment by rap2hpoutre** [comment]
Super ! Bon je trouve que c'est une bonne idée, donc vas-y ! Et bon courage pour l'optimisation...
